# Example Configuration file, all settings are defaulted to empty unless otherwise stated:
# NOTE: Not all the shown values are default (But the defaults are all documented in the proceeding comment and undocumented ones are empty by default)
listen: #HTTP server settings
  web: ":8080" #Listening address and port in the format address:port
  readTimeout: 30s #Read timeout of the HTTP servers as a duration, minimum: 1s
  writeTimeout: 30s #Write timeout of the HTTP servers as a duration, minimum: 1s
  identify: false #Send server identification headers
zones: #An array of zones
  - name: test #The name of the package set
    domains: ["localhost:8080"] #An array of domains this package set use (Each domain can only be registered with one zone)
    cssURL: "http://localhost/sheet.css" #A URL to the CSS file to use for outputted pages (If blank or not provided, no CSS is included)
    havePageContents: true #Output a header and link to the target repo
    basePath: "localhost" #The base-path, also known as, package name
    basePrefixURL: "http://localhost" #The base git URL
    usernameProvided: true #If the username is expected to be provided in requests to the server (When false the value of username can be used)
    username: "captain-alm" #The username to append to the start of a path under the prefix
    suffixDirectoryURL: "src/branch/master{/dir}" #The suffix location of the main branch for directory usage
    suffixFileURL: "src/branch/master{/dir}/{file}#L{line}" #The suffix location of the main branch for file usage
    rangeSupported: true #Are range requests supported
    pathLengthLimit: 0 #The length of the returned paths in the responses (Number of path entries); (If 0: defaults to 1, if the username is not expected to be provided by the request, otherwise defaulting to 2)
    cacheSettings: #Cache settings
      maxAge: 0 #The maximum age of the cache
      notModifiedUsingLastModified: true #Are the conditional headers attached to Last-Modified used to work out if to send a 304 Cache Redirect
      notModifiedUsingETags: true #Are the conditional headers attached to ETag used to work out if to send a 304 Cache Redirect

